In [1]:
import numpy as np

Practising reshaping of array

In [2]:
arr=np.array([1,2,3,4])

In [3]:
arr.shape

(4,)

In [4]:
arr.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [5]:
arr

array([1, 2, 3, 4])

### Linear regression with scikit learn

In [6]:
from sklearn.linear_model import LinearRegression

In [7]:
model=LinearRegression()

In [8]:
X=np.array([1,2,3,4,5,6,7,8,9,9.1,10,10.5,11.8,13,15.1,15.3,20,25,14,17.3,45,89,2.5,2.1,795,789,124,756,456,123,145,132,213,312,456,564,654,751,987,989,789,483,732]).reshape(-1,1)
Y=(2*X)+10
Y

array([[  12. ],
       [  14. ],
       [  16. ],
       [  18. ],
       [  20. ],
       [  22. ],
       [  24. ],
       [  26. ],
       [  28. ],
       [  28.2],
       [  30. ],
       [  31. ],
       [  33.6],
       [  36. ],
       [  40.2],
       [  40.6],
       [  50. ],
       [  60. ],
       [  38. ],
       [  44.6],
       [ 100. ],
       [ 188. ],
       [  15. ],
       [  14.2],
       [1600. ],
       [1588. ],
       [ 258. ],
       [1522. ],
       [ 922. ],
       [ 256. ],
       [ 300. ],
       [ 274. ],
       [ 436. ],
       [ 634. ],
       [ 922. ],
       [1138. ],
       [1318. ],
       [1512. ],
       [1984. ],
       [1988. ],
       [1588. ],
       [ 976. ],
       [1474. ]])

In [9]:
# using fit function we give data to the model.
# it requires 2d array .fit(X,Y)
model.fit(X,Y)

LinearRegression()

In [10]:
intercept=model.intercept_
slope=model.coef_

print(f"intercept is {intercept} and slope is {slope}")

intercept is [10.] and slope is [[2.]]


In [11]:
model.predict([[20]])

array([[50.]])

The main problem with linear regression is every dataset can't be visualised as a line, because in linear regression data points which have high variance have high "INFLUENCE" over the line parameters

In [12]:
model_2=LinearRegression()

In [13]:
Y_2=(X*X)+10
Y_2

array([[1.10000e+01],
       [1.40000e+01],
       [1.90000e+01],
       [2.60000e+01],
       [3.50000e+01],
       [4.60000e+01],
       [5.90000e+01],
       [7.40000e+01],
       [9.10000e+01],
       [9.28100e+01],
       [1.10000e+02],
       [1.20250e+02],
       [1.49240e+02],
       [1.79000e+02],
       [2.38010e+02],
       [2.44090e+02],
       [4.10000e+02],
       [6.35000e+02],
       [2.06000e+02],
       [3.09290e+02],
       [2.03500e+03],
       [7.93100e+03],
       [1.62500e+01],
       [1.44100e+01],
       [6.32035e+05],
       [6.22531e+05],
       [1.53860e+04],
       [5.71546e+05],
       [2.07946e+05],
       [1.51390e+04],
       [2.10350e+04],
       [1.74340e+04],
       [4.53790e+04],
       [9.73540e+04],
       [2.07946e+05],
       [3.18106e+05],
       [4.27726e+05],
       [5.64011e+05],
       [9.74179e+05],
       [9.78131e+05],
       [6.22531e+05],
       [2.33299e+05],
       [5.35834e+05]])

In [14]:
model_2.fit(X,Y_2)

LinearRegression()

In [15]:
print(f"intercept is {model_2.intercept_} and slope is {model_2.coef_}")

intercept is [-37570.07130243] and slope is [[824.57515701]]


In [16]:
model_2.predict([[20]])
#The result is no where near to the original value

array([[-21078.56816217]])

In [17]:
model_2.predict([[845]])

array([[659195.93637347]])

In [18]:
model_2.predict([[1000]])

array([[787005.08571047]])

In [19]:
model_2.predict([[800]])
#actual y value: 6,40,010

array([[622090.05430789]])

In [20]:
model_2.predict([[785]])
#actual y value: 6,16,235

array([[609721.42695269]])

Functions used:
*   .fit(X,Y)
*   .coef_, .intercept_
*   .predict(X_2D)




### Building linear reg from scratch.

Loss funtion:  𝐿(𝑤,𝑏)=1/2*(𝑦̂(𝑖) −𝑦(𝑖))^2
It's defined for single value of y.

cost function:
 𝐸(𝑚,𝑏)=1/2𝑛 ∑𝑖=1 to 𝑛(𝑦̂ (𝑖)−𝑦(𝑖))^2 = 1/2𝑛 ∑𝑖=1𝑛(𝑚𝑥(𝑖)+𝑏−𝑦(𝑖))^2


* partial diff
* gradient descent
* Normalizaion   
* denormalization




In [21]:
#Define points X & Y
X_=np.array([1,2,3,4,5,6,7,8,9,9.1,10,10.5,11.8,13,15.1,15.3,20,25,14,17.3,45,89,2.5,2.1,795,789,124,756,456,123,145,132,213,312,456,564,654,751,987,989,789,483,732]).reshape(-1,1)
Y_=(2*X_)+10

In [22]:
#define cost function
def E(m,b,X,Y):
  res=1/(2*len(X))*np.sum((m*X+b-Y)**2)
  return res

In [23]:
#define derivatives for gradient descent.
def dEdm(m,b,X,Y):
  res=1/len(X)*np.sum((m*X+b-Y)*X)
  return res

def dEdf(m,b,X,Y):
  res=1/len(X)*np.sum(m*X+b-Y)
  return res


In [24]:
#initialize some random m and b
m=1;b=1

def gradient_descent(m,b,X,Y,learning_rate=0.1,no_iter=1000):
  for i in range(no_iter):
    m_new= m - learning_rate*dEdm(m,b,X,Y)
    b_new= b - learning_rate*dEdf(m,b,X,Y)
    m=m_new
    b=b_new

    if i%100==0:
      print(f"For {i} iteration the cost function is {E(m,b,X,Y)}")
  return m,b


In [25]:
#normalizing
x_mean=np.mean(X_);x_std=np.std(X_)
y_mean=np.mean(Y_);y_std=np.std(Y_)

X_=(X_-x_mean)/x_std
Y_=(Y_-y_mean)/y_std

In [26]:
#Testing time
m,b=gradient_descent(m,b,X_,Y_)
print(f"The slope of the line {m}, intercept {b}")

For 0 iteration the cost function is 0.40500000000000014
For 100 iteration the cost function is 2.8573070390099356e-10
For 200 iteration the cost function is 2.0158526422327243e-19
For 300 iteration the cost function is 1.4237306553748039e-28
For 400 iteration the cost function is 1.7915627389648705e-35
For 500 iteration the cost function is 1.1197267118530441e-35
For 600 iteration the cost function is 2.2394534237060882e-36
For 700 iteration the cost function is 2.2394534237060882e-36
For 800 iteration the cost function is 0.0
For 900 iteration the cost function is 0.0
The slope of the line 1.0, intercept 6.938663342070573e-18


In [27]:
#predicting:
"""first we have to normalize input X,
    then denormalize the output
"""
x_input=np.array([10,15,14])
#normalize input
x_input_norm=(x_input-x_mean)/x_std

y_pred_norm=(m*x_input_norm)+b

In [28]:
#denormalize
y_pred=(y_pred_norm*y_std)+y_mean

print(f"The result of {x_input} is {y_pred}")


The result of [10 15 14] is [30. 40. 38.]
